platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'Memo' do
  inherit! :search_paths
  pod 'Reusable'
  pod 'SnapKit'
  pod 'SwiftFormat/CLI'
  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'Swinject'
end

target 'MemoCore' do
  inherit! :search_paths
  pod 'RealmSwift'
  pod 'Swinject'
end