# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvm-example-memo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mvvm-example-memo
  inherit! :search_paths
  pod 'RealmSwift'
  pod 'Reusable'
  pod 'SnapKit'
  pod 'SwiftFormat/CLI'
  pod 'SwiftGen'
  pod 'SwiftLint'
end
