# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Memo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Memo
  inherit! :search_paths
  pod 'RealmSwift'
  pod 'Reusable'
  pod 'SnapKit'
  pod 'SwiftFormat/CLI'
  pod 'SwiftGen'
  pod 'SwiftLint'
end
